Repository cherry-6lossom/6lossom, pull requests merged in 2023-04, with the labels that each got.

#200 Pull Request from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  README.md
  package-lock.json
  package.json
  public/assets/index-085f922b.js
  public/assets/index-d40730d2.js
  public/assets/react-9adfdfcb.js
  public/assets/react-ee5f4fb1.js
  public/index.html
  src/app/App.jsx
  src/data/backgroundImageList.js
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: 🐞 BugFix, 🥰 Accessibility

#201 Pull Request from cheery-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  public/assets/index-085f922b.js
  public/assets/index-d40730d2.js
  public/assets/react-9adfdfcb.js
  public/assets/react-ee5f4fb1.js
  public/index.html
  src/app/App.jsx
  src/data/backgroundImageList.js
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: 🐞 BugFix, 🥰 Accessibility

#203 Pull Request from Eonii2/6lossom/develop to cherry-6lossom/6lossom/develop
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#207 Pull Request from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/BackgroundCustomItem/BackgroundCustomItem.jsx
  src/components/BackgroundCustomList/BackgroundCustomList.jsx
  src/components/Flower/Flower.jsx
  src/components/FormInput/FormInput.jsx
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/LoginButton/LoginButton.jsx
  src/components/LongButton/LongButton.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/ModalButton/ModalButton.jsx
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/SideMenu/SideMenu.jsx
  src/components/UsageDescription/UsageDescription.jsx
  src/data/backgroundImageList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: 🥰 Accessibility, ✨ Feature

#208 Pull Request from Eonii2/6lossom/develop to cherry-6lossom/6lossom/develop
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: 🥰 Accessibility

#209 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  src/components/FormInput/FormInput.jsx
  src/components/Notification/Notification.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignUp/SignUpPage.jsx
Labels: 🥰 Accessibility, ✨ Feature, ✂ Modify

#210 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  .gitignore
  public/assets/index-085f922b.js
  public/assets/index-db8f7b2a.js
  public/assets/index.css
  public/assets/react-ed0a12b3.js
  public/assets/react-ee5f4fb1.js
  public/index.html
Labels: ⚙️setting

#211 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .gitignore
  public/assets/index-085f922b.js
  public/assets/index-db8f7b2a.js
  public/assets/index.css
  public/assets/react-ed0a12b3.js
  public/assets/react-ee5f4fb1.js
  public/index.html
  src/components/BackgroundCustomItem/BackgroundCustomItem.jsx
  src/components/BackgroundCustomList/BackgroundCustomList.jsx
  src/components/Flower/Flower.jsx
  src/components/FormInput/FormInput.jsx
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/LoginButton/LoginButton.jsx
  src/components/LongButton/LongButton.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/ModalButton/ModalButton.jsx
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/Notification/Notification.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/SideMenu/SideMenu.jsx
  src/components/UsageDescription/UsageDescription.jsx
  src/data/backgroundImageList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignUp/SignUpPage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: ⚙️setting

#217 Pull Request from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.jsx
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/SideMenu/SideMenu.jsx
  src/components/SideMenu/SideMenu.module.scss
  src/data/blossomInfoList.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: 🥰 Accessibility, ✂ Modify, 🔨 Refactor

#219 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/FormInput/FormInput.jsx
  src/components/MessageDetail/MessageDetail.jsx
  src/components/MessageItem/MessageItem.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.jsx
Labels: ✂ Modify, ⚙️setting

#222 Pull request from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️setting

#224 Pull request from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  public/assets/index-82a86cc2.js
  public/assets/index.css
  public/index.html
  src/data/backgroundImageList.ts
  src/data/blossomInfoList.ts
Labels: 🐞 BugFix
