Repository cherry-6lossom/6lossom, pull requests merged in 2023-03, with the labels that each got.

#52 Merge from SSY1203/develop to 6lossom/develop
  package-lock.json
  package.json
  src/app/App.jsx
  src/assets/brand-logo/facebook-white.png
  src/assets/brand-logo/google.png
  src/assets/brand-logo/twitter-blue.png
  src/assets/brand-logo/twitter-white.png
  src/components/LoginButton/LoginButton.jsx
  src/firebase/app.js
  src/firebase/auth/useCreateAuthUser.js
  src/firebase/firestore/useReadData.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/styles/base/_base.scss
Labels: ✨ Feature

#55 사용자 정보 렌더링 시간 차 오류 해결
  src/components/LoginButton/LoginButton.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
Labels: 🐞 BugFix

#62 Merge from SSY1203/develop to 6lossom/SSY1203
  src/app/App.jsx
  src/components/BackgroundCustomItem/BackgroundCustomItem.jsx
  src/components/BackgroundCustomItem/BackgroundCustomItem.module.scss
  src/components/BackgroundCustomList/BackgroundCustomList.jsx
  src/components/HeaderTitle/HeaderTitle.jsx
  src/components/HeaderTitle/HeaderTitle.module.scss
  src/components/LongButton/LongButton.jsx
  src/components/LongButtonList/LongButtonList.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButton/ShortButton.module.scss
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/UsageDescription/UsageDescription.jsx
  src/components/UsageDescription/UsageDescription.module.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
Labels: ✂ Modify

#75 Merge from qpsqps321/6lossom/develop to cherry-6lossom/6lossom/develop
  src/app/App.jsx
  src/assets/login/check-default.png
  src/assets/login/check-pink.png
  src/assets/login/eye.png
  src/assets/login/eyeClosed.png
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.scss
  src/components/LoginButton/LoginButton.jsx
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignIn.js
  src/firebase/auth/useSignOut.js
  src/firebase/auth/useSignUp.js
  src/firebase/firestore/useCreateAuthUser.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.module.scss
Labels: ✨ Feature, ⚙️setting

#77 Merge from SSY1203/develop to 6lossom/develop
  src/app/App.jsx
  src/components/BackgroundCustomItem/BackgroundCustomItem.jsx
  src/components/BackgroundCustomList/BackgroundCustomList.jsx
  src/components/HeaderTitle/HeaderTitle.jsx
  src/components/HeaderTitle/HeaderTitle.module.scss
  src/components/LoginButton/LoginButton.jsx
  src/components/LongButtonList/LongButtonList.jsx
  src/components/OriginTree/OriginTree.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/UsageDescription/UsageDescription.jsx
  src/components/UsageDescription/UsageDescription.module.scss
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignIn.js
  src/firebase/auth/useSignOut.js
  src/firebase/auth/useSignUp.js
  src/firebase/firestore/useCreateAuthUser.js
  src/firebase/firestore/useUpdateData.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignUp/SignUpPage.jsx
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#88 Develop from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.scss
  src/components/Notification/Notification.jsx
  src/firebase/auth/useSignIn.js
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.module.scss
Labels: ✨ Feature, 🔨 Refactor

#89 Merge from SSY1203/develop to 6lossom/develop
  src/assets/brand-logo/github-logo.png
  src/assets/main-page/main-tree.png
  src/assets/react.svg
  src/components/BackgroundCustomItem/BackgroundCustomItem.module.scss
  src/components/FormInput/FormInput.jsx
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/HamburgerButton/HamburgerButton.module.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/HeaderTitle/HeaderTitle.jsx
  src/components/HeaderTitle/HeaderTitle.module.scss
  src/components/LongButton/LongButton.jsx
  src/components/LongButton/LongButton.module.scss
  src/components/LongButtonList/LongButtonList.jsx
  src/components/LongButtonList/LongButtonList.module.scss
  src/components/OriginTree/OriginTree.jsx
  src/components/OriginTree/OriginTree.module.scss
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButton/ShortButton.module.scss
  src/components/SideMenu/SideMenu.jsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/UsageDescription/UsageDescription.jsx
  src/components/UsageDescription/UsageDescription.module.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#90 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/FormInput/FormInput.jsx
Labels: 🐞 BugFix

#93 Develop from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  src/firebase/app.js
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignUp/SignUpPage.jsx
Labels: ✨ Feature, 🔨 Refactor

#98 Merge to SSY1203/develop from 6lossom/develop
  src/assets/icon/Hamburger.png
  src/assets/icon/moon-message.png
  src/components/LoginButton/LoginButton.jsx
  src/components/SideMenu/SideMenu.jsx
  src/firebase/app.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/styles/theme/_theme.scss
Labels: ✂ Modify

#105 Merge from qpsqps123/6lossom/develop to cherry-6losoom/6lossom/develop
  src/components/MessageDetail/MessageDetail.jsx
  src/components/MessageDetail/MessageDetail.module.scss
  src/components/MessageItem/MessageItem.jsx
  src/components/MessageItem/MessageItem.module.scss
  src/components/MessageList/MessageList.jsx
  src/components/MessageList/MessageList.module.scss
  src/components/ModalMessage/ModalMessage.jsx
  src/contexts/messageContext.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
Labels: ✨ Feature, ⚙️setting

#111 Merge from SSY1203/develop to 6lossom/develop
  package-lock.json
  package.json
  src/components/Flower/Flower.jsx
  src/components/Flower/Flower.module.scss
  src/components/LoginButton/LoginButton.jsx
  src/components/MessageDetail/MessageDetail.jsx
  src/components/MessageItem/MessageItem.jsx
  src/components/MessageList/MessageList.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/ShortButtonList/ShortButtonList.module.scss
  src/components/TotalMessage/TotalMessage.jsx
  src/contexts/flowerContext.jsx
  src/firebase/app.js
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  vite.config.js
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#112 Merge from KMSWN/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomItem/MessageCustomItem.module.scss
  src/components/MessageCustomTotal/MessageCustomTotal.jsx
  src/components/MessageCustomTotal/MessageCustomTotal.module.scss
  src/components/ModalMessage/ModalMessage.jsx
  src/components/TotalMessage/TotalMessage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.module.scss
Labels: 🐞 BugFix, ✨ Feature

#117 Merge from SSY1203/develop to 6lossom/develop
  src/app/App.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomItem/MessageCustomItem.module.scss
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageCustomList/MessageCustomList.module.scss
  src/components/MessageCustomTotal/MessageCustomTotal.jsx
  src/components/MessageCustomTotal/MessageCustomTotal.module.scss
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/contexts/messageCustomContext.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MessageCustomPage.jsx/MessageCustomPage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/SignUp/SignUpPage.jsx
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify, 🔨 Refactor

#118 Merge from Eonii2/develop to 6lossom/develop
  src/app/App.jsx
  src/components/LongButton/LongButton.module.scss
  src/components/LongButtonList/LongButtonList.module.scss
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/MessageInputContainer/MessageInputContainer.module.scss
  src/components/ModalButton/ModalButton.jsx
  src/components/ModalButton/ModalButton.module.scss
  src/components/ModalButtonList/ModalButtonList.jsx
  src/components/ModalButtonList/ModalButtonList.module.scss
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalEnroll/ModalEnroll.module.scss
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.module.scss
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.module.scss
  src/components/UsageDescription/UsageDescription.module.scss
  src/firebase/app.js
  src/pages/HomePage/HomePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.module.scss
  src/styles/theme/_theme.scss
Labels: ✨ Feature

#122 Merge from SSY1203/develop to 6lossom/develop
  src/app/App.jsx
  src/assets/Spinner-1s-200px.svg
  src/components/BackgroundCustomItem/BackgroundCustomItem.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.module.scss
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/ShortButtonList/ShortButtonList.module.scss
  src/components/SideMenu/SideMenu.jsx
  src/firebase/firestore/useCreateAuthUser.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.module.scss
  src/styles/theme/_theme.scss
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify, 🔨 Refactor

#125 Merge from SSY1203/develop to 6lossom/develop
  src/components/Flower/Flower.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#129 Merge from SSY1203/develop to 6lossom/develop
  src/components/Flower/Flower.jsx
  src/components/LongButton/LongButton.jsx
  src/components/LongButtonList/LongButtonList.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: ✨ Feature

#130 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.module.scss
Labels: ✨ Feature, 🔨 Refactor

#133 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
Labels: ✂ Modify

#136 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
Labels: ✂ Modify

#138 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.jsx
  src/components/Flower/Flower.module.scss
  src/components/Header/Header.module.scss
  src/components/LongButton/LongButton.module.scss
  src/components/LongButtonList/LongButtonList.module.scss
  src/components/MessageCustomItem/MessageCustomItem.module.scss
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/OriginTree/OriginTree.jsx
  src/components/OriginTree/OriginTree.module.scss
  src/components/ShortButton/ShortButton.module.scss
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/MessageCustomPage/MessageCustomPage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  src/pages/SignUp/SignUpPage.jsx
  src/styles/base/_base.scss
  src/styles/utils/_layout.scss
Labels: ✂ Modify

#146 Develop from qpsqps123/6lossom/6lossom to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.module.scss
  src/components/LongButton/LongButton.module.scss
  src/components/LongButtonList/LongButtonList.module.scss
  src/components/MessageInputContainer/MessageInputContainer.module.scss
  src/components/MessageList/MessageList.module.scss
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalEnroll/ModalEnroll.module.scss
  src/components/ShortButton/ShortButton.module.scss
  src/pages/HomePage/HomePage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.jsx
  src/pages/SignUp/SignUpPage.module.scss
  src/pages/WriteMessagePage/WriteMessagePage.module.scss
  src/styles/utils/_layout.scss
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify

#155 Merge from qpsqps123/6lossom/develop to cherry-6lossom/6lossom/develop
  src/assets/main-page/main-tree-with-flower.png
  src/components/BackgroundCustomItem/BackgroundCustomItem.module.scss
  src/components/BackgroundCustomList/BackgroundCustomList.jsx
  src/components/BackgroundCustomList/BackgroundCustomList.module.scss
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.module.scss
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.module.scss
  src/components/ShortButton/ShortButton.module.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/styles/utils/_layout.scss
Labels: ✂ Modify

#158 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/BackgroundCustomItem/BackgroundCustomItem.module.scss
  src/components/Flower/Flower.module.scss
  src/components/FormInput/FormInput.module.scss
  src/components/HeaderTitle/HeaderTitle.module.scss
  src/components/MessageDetail/MessageDetail.module.scss
  src/components/MessageItem/MessageItem.module.scss
  src/components/ModalButtonList/ModalButtonList.jsx
  src/components/ModalButtonList/ModalButtonList.module.scss
  src/components/ModalEnroll/ModalEnroll.module.scss
  src/components/ModalMessage/ModalMessage.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.module.scss
  src/components/OriginFlower/OriginFlower.jsx
  src/components/ShortButton/ShortButton.module.scss
  src/components/SideMenu/SideMenu.jsx
  src/components/SideMenu/SideMenu.module.scss
  src/components/TotalMessage/TotalMessage.jsx
  src/components/UsageDescription/UsageDescription.module.scss
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/MessageCustomPage/MessageCustomPage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/ShareTreePage/ShareTreePage.module.scss
  src/pages/SignIn/SignInPage.jsx
  src/pages/SignIn/SignInPage.module.scss
  src/pages/SignUp/SignUpPage.module.scss
  src/pages/WriteMessagePage/WriteMessagePage.module.scss
  src/styles/utils/_layout.scss
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify

#160 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/Flower/Flower.jsx
  src/components/Flower/Flower.module.scss
  src/components/FormInput/FormInput.module.scss
  src/components/MessageInputContainer/MessageInputContainer.module.scss
  src/components/ModalEnroll/ModalEnroll.module.scss
  src/components/ProjectInfoButton/ProjectInfoButton.module.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/MakeTreePage/MakeTreePage.jsx
  src/pages/MakeTreePage/MakeTreePage.module.scss
  src/pages/ShareTreePage/ShareTreePage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.module.scss
Labels: 🐞 BugFix, ✂ Modify

#161 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  dist/assets/Spinner-69699739.svg
  dist/assets/bg-night-ab5492a0.png
  dist/assets/bg-pink-b7ef3b27.png
  dist/assets/bg-sky-fdca7656.png
  dist/assets/cherry-blossom1.png
  dist/assets/cherry-blossom2.png
  dist/assets/cherry-blossom3.png
  dist/assets/cherry-blossom4.png
  dist/assets/github-logo-60f99b69.png
  dist/assets/index-38384207.css
  dist/assets/index-4e9ee01c.js
  dist/assets/main-logo-d18ef130.png
  dist/assets/main-tree-2d50ef6a.png
  dist/assets/main-tree-with-flower-c6465aca.png
  dist/assets/message-9547ed1e.png
  dist/assets/moon-message-e10a2167.png
  dist/assets/neodgm-263ed745.eot
  dist/assets/neodgm-42f453d9.woff2
  dist/assets/neodgm-4dd932c1.ttf
  dist/assets/neodgm-f6fd7599.woff
  dist/assets/project-info-5e0a0510.png
  dist/assets/select-bg-night-f2910adf.png
  dist/assets/select-bg-pink-5d99d628.png
  dist/assets/select-bg-sky-cb1e8a17.png
  dist/assets/x-square-4cd9651e.png
  dist/index.html
  public/vite.svg
  src/assets/loading/Spinner.svg
  src/components/Flower/Flower.jsx
  src/firebase/firestore/useCreateAuthUser.js
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/ShareTreePage/ShareTreePage.jsx
Labels: ✂ Modify, ⚙️setting

#163 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/ModalButton/ModalButton.jsx
  src/components/ModalButtonList/ModalButtonList.jsx
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/SideMenu/SideMenu.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: ✂ Modify

#164 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  src/components/HamburgerButton/HamburgerButton.jsx
  src/components/MessageCustomItem/MessageCustomItem.jsx
  src/components/MessageCustomList/MessageCustomList.jsx
  src/components/MessageInputContainer/MessageInputContainer.jsx
  src/components/ModalButton/ModalButton.jsx
  src/components/ModalButtonList/ModalButtonList.jsx
  src/components/ModalEnroll/ModalEnroll.jsx
  src/components/ModalProjectInfo/ModalProjectInfo.jsx
  src/components/ProjectInfoButton/ProjectInfoButton.jsx
  src/components/ShortButton/ShortButton.jsx
  src/components/ShortButtonList/ShortButtonList.jsx
  src/components/SideMenu/SideMenu.jsx
  src/pages/MessageCustomPage/MessageCustomPage.jsx
  src/pages/WriteMessagePage/WriteMessagePage.jsx
Labels: ✂ Modify

#165 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  dist/assets/index-3af8effb.js
  dist/index.html
  src/components/SideMenu/SideMenu.jsx
Labels: ✂ Modify

#166 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  dist/assets/index-3af8effb.js
  dist/index.html
  src/components/SideMenu/SideMenu.jsx
Labels: ✂ Modify

#167 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  src/assets/icon/Hamburger.png
Labels: ✂ Modify

#168 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  src/assets/icon/Hamburger.png
Labels: ✂ Modify

#169 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  dist/assets/download.png
Labels: ✂ Modify

#170 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  dist/assets/download.png
Labels: ✂ Modify

#175 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  vercel.json
Labels: 🐞 BugFix

#177 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  vercel.json
Labels: 🐞 BugFix

#178 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  vercel.json
Labels: 🐞 BugFix

#187 Merge from SSY1203/6lossom/develop to cherry-6lossom/6lossom/develop
  index.html
  public/index.html
Labels: ✨ Feature

#188 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  index.html
  public/index.html
Labels: ✨ Feature

#190 Merge from cherry-6lossom/6lossom/develop to cherry-6lossom/6lossom/main
  public/assets/index-d711aea1.js
  public/index.html
  src/pages/MessageCustomPage/MessageCustomPage.jsx
Labels: 🐞 BugFix
